### ISSUE TITLE
Handshake exception in high concurrency

### ISSUE THREAD

**Issue by silence-coding** [tokio-rs/tls#26] opened 2020-08-29 07:30 UTC
When I perform a pressure test using Wrk, a few connection handshakes fail.
The details are as follows:
Use Wrk to send 20k request packets to test service A, and test service A forwards the packets to test service B. For a few connections, the client of test service A considers that the handshake is successful, but the server of test service B considers that the handshake sent by test service A fails. The client and server of test service A are both tokio-trustls, and test service B is also tokio-trustls.
The wrk pressure test command is as follows:
wrk -t 300 -c 3000 -d 1 m -T 10 --script=xxx.lua --latency https://***/ssssss

**Comment by quininer** [comment] 2020-08-29 07:45
Can you give a reproduce example?

**Comment by silence-coding** [comment] 2020-08-30 07:49
The server times out when the code "acceptor.accept(io).await" is executed. The I/O is tokio tcpstream and the certificate is rsa two-way authentication.

**Comment by silence-coding** [comment] 2020-08-30 07:52
The client uses the method "connect " of tokio-rustls.

**Comment by silence-coding** [comment] 2020-08-30 08:22
the server handshake timout is 30 sec, the client  handshake timout is 10 sec.  The CPU usage of the client and server accounts for less than a quarter of the system CPU.

**Comment by silence-coding** [comment] 2020-08-30 08:33
Faulty packets

![截图](https://user-images.githubusercontent.com/32766901/91654791-7a142000-eade-11ea-8ed1-9e50e8c9219f.PNG)

**Comment by quininer** [comment] 2020-08-30 10:42
I cannot reproduce the problem, can you provide your test code?

I don't think that concurrency will affect tls handshake. from your description, `handshake fail` is actually a timeout instead of an tls error?

**Comment by silence-coding** [comment] 2020-09-01 06:44
I'm sorry, I can't provide the current code. However, this error is not caused by handshake timeout. The timeout interval of the client is 10s and that of the server is 30s. If the handshake fails because of timeout, the client reports timeout first. However, the current problem is that the client considers that the handshake is successful, but the server considers that the handshake times out.

**Comment by silence-coding** [comment] 2020-09-01 06:46
According to the captured packets, the server (IP 58) may be waiting for the client (IP 53) to send a Change Cipher Sepc packet to the server.

**Comment by mleonhard** [comment] 2020-11-13 09:48
There are many potential causes of connection timeouts:
- Most networking equipment is flaky under high load.  When load is high, they drop some packets.  You can detect these lost packets by capturing packets from both machines.  TCP is resilient against dropped packets when the OS uses appropriate  [TCP retransmit timings](https://pracucci.com/linux-tcp-rto-min-max-and-tcp-retries2.html).
- Server process not utilizing all cores because of misconfiguration or container restrictions.  Check per-core cpu utilization.
- Container network throttling.  The container may be dropping the packets.  To detect this, capture packets on the container's internal interface.
- Tokio worker threads stuck on blocking IO.  Check per-thread cpu utilization.
- Server process doing something expensive in the accept loop or in connection handler before starting TLS negotiation.  Logging can cause slowdowns.
- Host machine is custom built and its power supply is too small.  This problem shows under heavy load.  It can cause all kinds of strange machine errors.  Check the kernel logs for strange errors.
- Host machine internal bus congestion.  The internal bus serves GPUs, SSD, and NICs.  Network throughput can go down when the NIC shares a PCI channel with another device and that device is used heavily.  Check the NIC queue lengths.
- Cosmic rays corrupting TCP packets in RAM.  This doesn't affect 1-minute tests.
- Bug in core application libraries

It's been 1.5 months since you reported this issue.  What happened?

**Comment by silence-coding** [comment] 2021-04-21 03:39
@mleonhard Thank you for your reply.
For reasons of energy, I'm not following this issue, but I'm going to go through H2 and get around the situation.

**Comment by mleonhard** [comment] 2021-04-21 23:47
@silence-coding If you're not going to pursue the issue further, how about closing it?  That would be kind to the project maintainers.

**Comment by silence-coding** [comment] 2021-04-25 06:24
@mleonhard All right.

**Closed** 2021-04-25 06:24 UTC
